// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function readViteEnv(name: string): string | undefined {
  const value = typeof import.meta !== 'undefined' ? import.meta.env?.[name] : undefined;
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

function readProcessEnv(name: string): string | undefined {
  const value = typeof process !== 'undefined' ? process.env?.[name] : undefined;
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

function resolveSupabaseProjectId(): string | undefined {
  return readViteEnv('VITE_SUPABASE_PROJECT_ID') || readProcessEnv('SUPABASE_PROJECT_ID');
}

function resolveSupabaseUrl(): string | undefined {
  const configuredUrl = readViteEnv('VITE_SUPABASE_URL') || readProcessEnv('SUPABASE_URL');
  if (configuredUrl) return configuredUrl;

  const projectId = resolveSupabaseProjectId();
  return projectId ? `https://${projectId}.supabase.co` : undefined;
}

function resolveSupabasePublishableKey(): string | undefined {
  return readViteEnv('VITE_SUPABASE_PUBLISHABLE_KEY') || readProcessEnv('SUPABASE_PUBLISHABLE_KEY');
}

const RESOLVED_SUPABASE_URL = resolveSupabaseUrl();
const RESOLVED_SUPABASE_PUBLISHABLE_KEY = resolveSupabasePublishableKey();

export const supabaseConfig = {
  url: RESOLVED_SUPABASE_URL,
  hasUrl: Boolean(RESOLVED_SUPABASE_URL),
  hasPublishableKey: Boolean(RESOLVED_SUPABASE_PUBLISHABLE_KEY),
};

export const isSupabaseConfigured = Boolean(
  RESOLVED_SUPABASE_URL && RESOLVED_SUPABASE_PUBLISHABLE_KEY
);

function createSupabaseClient() {
  const SUPABASE_URL = RESOLVED_SUPABASE_URL || 'https://placeholder.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY = RESOLVED_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

  if (!isSupabaseConfigured) {
    console.warn('[Supabase] Missing VITE_SUPABASE_PUBLISHABLE_KEY. Please add it to your Vercel Project Settings > Environment Variables.');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
